spring:
  datasource:
    url: jdbc:postgresql://db:5432/dictionary
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
    database-change-log-table: notification-gate-change-log-table
    database-change-log-lock-table: notification-gate-change-log-lock-table
    parameters:
      default-schema-prefix: public
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
      fail-on-unknown-properties: false

logging:
  level:
    org.zalando.logbook.Logbook: TRACE

logbook:
  format:
    style: json
  include:
    - '/v1/**'

springdoc:
  packages-to-scan: "ge.ka.ubani.georgiabackend.controller"